plugins {
    id 'com.android.application'
}

android {
    namespace 'codes.var.tweak.proxyswitcher'
    compileSdk 36

    defaultConfig {
        applicationId 'codes.var.tweak.proxyswitcher'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            manifest.srcFile '../AndroidManifest.xml'
            java.srcDirs = ['../src/main/java']
            res.srcDirs = ['../src/main/res']
            assets.srcDirs = ['../src/main/assets']
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
